In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df_train = pd.read_csv('/content/train.csv')
df_test = pd.read_csv('/content/test.csv')

In [ ]:
df_train.shape,df_test.shape

((891, 12), (418, 11))

In [ ]:
df_train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
df_test.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
Id = df_test.iloc[:,0]

In [ ]:
df_train.drop(["Ticket","Cabin"],axis = 1,inplace=True)
df_test.drop(["Ticket","Cabin"],axis = 1,inplace=True)

In [ ]:
df_train.head()

PassengerId  Survived  Pclass  ... Parch     Fare  Embarked
0            1         0       3  ...     0   7.2500         S
1            2         1       1  ...     0  71.2833         C
2            3         1       3  ...     0   7.9250         S
3            4         1       1  ...     0  53.1000         S
4            5         0       3  ...     0   8.0500         S

[5 rows x 10 columns]

In [ ]:
df_test.head()

PassengerId  Pclass  ...     Fare Embarked
0          892       3  ...   7.8292        Q
1          893       3  ...   7.0000        S
2          894       2  ...   9.6875        Q
3          895       3  ...   8.6625        S
4          896       3  ...  12.2875        S

[5 rows x 9 columns]

In [ ]:
temp = df_train['Name'].values

In [ ]:
st=[]
for i in temp:
  a = i.split(" ")
  for k in a:
    if "." in k:
      st.append(k)
      break

In [ ]:
st = np.array(st)
df_train["New_name"]=st

In [ ]:
df_train['New_name'].unique()

array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Don.', 'Rev.', 'Dr.', 'Mme.',
       'Ms.', 'Major.', 'Lady.', 'Sir.', 'Mlle.', 'Col.', 'Capt.',
       'Countess.', 'Jonkheer.'], dtype=object)

In [ ]:
temp1 = df_test['Name'].values

In [ ]:
st2=[]
for i in temp1:
  a = i.split(" ")
  for k in a:
    if "." in k:
      if k=='Dona.':
        k='Don.'
      st2.append(k)
      break

In [ ]:
st2 = np.array(st2)
df_test["New_name"]=st2

In [ ]:
df_test['New_name'].unique()

array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Ms.', 'Col.', 'Rev.', 'Dr.',
       'Don.'], dtype=object)

In [ ]:
df_train.drop(["Name"],axis = 1,inplace=True)
df_test.drop(["Name"],axis = 1,inplace=True)

In [ ]:
df_train.head()

PassengerId  Survived  Pclass     Sex  ...  Parch     Fare  Embarked  New_name
0            1         0       3    male  ...      0   7.2500         S       Mr.
1            2         1       1  female  ...      0  71.2833         C      Mrs.
2            3         1       3  female  ...      0   7.9250         S     Miss.
3            4         1       1  female  ...      0  53.1000         S      Mrs.
4            5         0       3    male  ...      0   8.0500         S       Mr.

[5 rows x 10 columns]

In [ ]:
df_test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked New_name
0          892       3    male  34.5      0      0   7.8292        Q      Mr.
1          893       3  female  47.0      1      0   7.0000        S     Mrs.
2          894       2    male  62.0      0      0   9.6875        Q      Mr.
3          895       3    male  27.0      0      0   8.6625        S      Mr.
4          896       3  female  22.0      1      1  12.2875        S     Mrs.

In [ ]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
New_name         0
dtype: int64

In [ ]:
embarked =list(df_train['Embarked'].mode())

In [ ]:
df_train['Age'].fillna(df_train['Age'].mean(),inplace=True)
df_train['Embarked'].fillna(embarked[0],inplace=True)

In [ ]:
df_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
New_name       0
dtype: int64

In [ ]:
df_test.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
New_name        0
dtype: int64

In [ ]:


df_test['Age'].fillna(df_test['Age'].mean(),inplace=True)
df_test['Fare'].fillna(df_test['Fare'].mean(),inplace=True)

In [ ]:
df_test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
New_name       0
dtype: int64

In [ ]:
df_train.head()

PassengerId  Survived  Pclass     Sex  ...  Parch     Fare  Embarked  New_name
0            1         0       3    male  ...      0   7.2500         S       Mr.
1            2         1       1  female  ...      0  71.2833         C      Mrs.
2            3         1       3  female  ...      0   7.9250         S     Miss.
3            4         1       1  female  ...      0  53.1000         S      Mrs.
4            5         0       3    male  ...      0   8.0500         S       Mr.

[5 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_S = LabelEncoder()
le_E = LabelEncoder()
le_N = LabelEncoder()

In [ ]:
df_train['Sex'] = le_S.fit_transform(df_train['Sex'])
df_train['Embarked'] = le_E.fit_transform(df_train['Embarked'])
df_train['New_name'] = le_N.fit_transform(df_train['New_name'])

In [ ]:
df_test['Sex'] = le_S.transform(df_test['Sex'])
df_test['Embarked'] = le_E.transform(df_test['Embarked'])
df_test['New_name'] = le_N.transform(df_test['New_name'])

In [ ]:
df_train.head()

PassengerId  Survived  Pclass  Sex  ...  Parch     Fare  Embarked  New_name
0            1         0       3    1  ...      0   7.2500         2        12
1            2         1       1    0  ...      0  71.2833         0        13
2            3         1       3    0  ...      0   7.9250         2         9
3            4         1       1    0  ...      0  53.1000         2        13
4            5         0       3    1  ...      0   8.0500         2        12

[5 rows x 10 columns]

In [ ]:
df_test.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  New_name
0          892       3    1  34.5      0      0   7.8292         1        12
1          893       3    0  47.0      1      0   7.0000         2        13
2          894       2    1  62.0      0      0   9.6875         1        12
3          895       3    1  27.0      0      0   8.6625         2        12
4          896       3    0  22.0      1      1  12.2875         2        13

In [ ]:
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df_train[col]))

In [ ]:
dummies2 = []
cols2 = ['Pclass', 'Sex', 'Embarked']
for col2 in cols2:
    dummies2.append(pd.get_dummies(df_test[col2]))

In [ ]:
titanic_dummies2 = pd.concat(dummies2, axis=1)

In [ ]:


titanic_dummies = pd.concat(dummies, axis=1)

In [ ]:
df_train = pd.concat((df_train,titanic_dummies), axis=1)

In [ ]:
df_test = pd.concat((df_test,titanic_dummies2), axis=1)

In [ ]:
df_train = df_train.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

In [ ]:
df_test = df_test.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

In [ ]:
df_train.head()

PassengerId  Survived   Age  SibSp  Parch     Fare  ...  3  0  1  0  1  2
0            1         0  22.0      1      0   7.2500  ...  1  0  1  0  0  1
1            2         1  38.0      1      0  71.2833  ...  0  1  0  1  0  0
2            3         1  26.0      0      0   7.9250  ...  1  1  0  0  0  1
3            4         1  35.0      1      0  53.1000  ...  0  1  0  0  0  1
4            5         0  35.0      0      0   8.0500  ...  1  0  1  0  0  1

[5 rows x 15 columns]

In [ ]:
df_test.head()

PassengerId   Age  SibSp  Parch     Fare  New_name  1  2  3  0  1  0  1  2
0          892  34.5      0      0   7.8292        12  0  0  1  0  1  0  1  0
1          893  47.0      1      0   7.0000        13  0  0  1  1  0  0  0  1
2          894  62.0      0      0   9.6875        12  0  1  0  0  1  0  1  0
3          895  27.0      0      0   8.6625        12  0  0  1  0  1  0  0  1
4          896  22.0      1      1  12.2875        13  0  0  1  1  0  0  0  1

In [ ]:
x = df_train.iloc[:,2:].values
y = df_train.iloc[:,1].values
X_test = df_test.iloc[:,1:].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
X_test = sc.transform(X_test)

In [ ]:
# from sklearn.preprocessing import OneHotEncoder
# one = OneHotEncoder()
# y_train = one.fit_transform(y_train.reshape(-1,1))
# y_test = one.fit_transform(y_test.reshape(-1,1))

In [ ]:
y_train.shape,x_train.shape

((623,), (623, 13))

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=2)
x_train = lda.fit_transform(x_train,y_train)
x_test = lda.transform(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:463: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(13, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:469: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)


#KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=11,n_jobs=-1)
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=11, p=2,
                     weights='uniform')

In [ ]:
clf.score(x_train,y_train)

0.8041733547351525

In [ ]:
clf.score(x_test,y_test)

0.8395522388059702

In [ ]:
param2 = {
    "n_neighbors" : [5,7,11,13],
    "metric" : ['minkowski','mae']
}

In [ ]:
from sklearn.model_selection import GridSearchCV
clf_grid = GridSearchCV(estimator=clf,param_grid=param2,n_jobs=-1,cv=3)
clf_grid.fit(x_train,y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=-1,
                                            n_neighbors=11, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=-1,
             param_grid={'metric': ['minkowski', 'mae'],
                         'n_neighbors': [5, 7, 11, 13]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
clf_grid.best_params_

{'metric': 'minkowski', 'n_neighbors': 11}

In [ ]:
predictions = clf.predict(X_test)

In [ ]:
predictions[:10]

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [ ]:
Id = np.array(Id)

In [ ]:
df = pd.DataFrame(Id)
# df2 = pd.DataFrame(predictions)

In [ ]:
# predictions = pd.concat([df,df2], axis=1)
# predictions.columns=['PassengerId','Survived']

In [ ]:
# predictions.head()

In [ ]:
# predictions.to_csv("Prediction.csv")

#XGBOOST

In [ ]:
from xgboost import XGBClassifier
clf_xgb = XGBClassifier()
clf_xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
# XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
#               colsample_bynode=1, colsample_bytree=1, gamma=0,
#               learning_rate=0.2, max_delta_step=0, max_depth=3,
#               min_child_weight=1, missing=None, n_estimators=40, n_jobs=-1,
#               nthread=None, objective='binary:logistic', random_state=0,
#               reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
#               silent=None, subsample=1, verbosity=1)

In [ ]:
pred_xgb = clf_xgb.predict(x_train)
clf_xgb.score(x_train,y_train)*100

86.51685393258427

In [ ]:
clf_xgb.score(x_test,y_test)*100

80.22388059701493

In [ ]:
param2 = {
    "n_estimators":[40,30,25,50],
    "learning_rate":[0.1,0.2,0.3,0.5],
    "max_depth":[10,20,30,40]
}

In [ ]:
from sklearn.model_selection import GridSearchCV
clf_grid = GridSearchCV(estimator=clf_xgb,param_grid=param2,n_jobs=-1,cv=3)
clf_grid.fit(x_train,y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.5],
                         'max_depth': [10, 20, 30, 40],
                         'n_estimators': [40, 30, 25, 50]},

In [ ]:
clf_grid.best_params_

{'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 25}

In [ ]:
clf_grid.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=20,
              min_child_weight=1, missing=None, n_estimators=25, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
predictions_Xgb = clf_xgb.predict(X_test)

In [ ]:
predictions_svc = clf_svc.predict(X_test)

In [ ]:
df3 = pd.DataFrame(predictions_Xgb)

In [ ]:
df4 = pd.DataFrame(predictions_svc)

In [ ]:
predictions_Xgb = pd.concat([df,df3], axis=1)
predictions_Xgb.columns=['PassengerId','Survived']

In [ ]:
predictions_svc = pd.concat([df,df4], axis=1)
predictions_svc.columns=['PassengerId','Survived']

In [ ]:
predictions_Xgb.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [ ]:
predictions_svc.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [ ]:
predictions_Xgb.to_csv("Prediction_Xgbc.csv")

In [ ]:
predictions_svc.to_csv("Prediction_svc.csv")

#AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
clf_adb = AdaBoostClassifier(n_estimators=50,learning_rate=0.1)
clf_adb.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.1,
                   n_estimators=50, random_state=None)

In [ ]:
clf_adb.score(x_train,y_train)*100

79.61476725521669

In [ ]:
clf_adb.score(x_test,y_test)*100

80.59701492537313

In [ ]:
param3 = {
    "n_estimators":[40,30,25,50],
    "learning_rate":[0.1,0.2,0.3,0.5]
}

In [ ]:
from sklearn.model_selection import GridSearchCV
clf_grid = GridSearchCV(estimator=clf_adb,param_grid=param3,n_jobs=-1,cv=3)
clf_grid.fit(x_train,y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                          base_estimator=None,
                                          learning_rate=0.1, n_estimators=50,
                                          random_state=None),
             iid='deprecated', n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.5],
                         'n_estimators': [40, 30, 25, 50]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
clf_grid.best_params_

{'learning_rate': 0.1, 'n_estimators': 50}

#ANN

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

Using TensorFlow backend.


In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(units=64,activation='relu',input_shape=(3,)))
model.add(Dropout(rate=0.2))

In [ ]:
model.add(Dense(units=32,activation='relu'))
model.add(Dropout(rate=0.2))

In [ ]:
model.add(Dense(units=1,activation='sigmoid'))

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                256       
_________________________________________________________________
dropout_3 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 32)                2080      
_________________________________________________________________
dropout_4 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 33        
Total params: 2,369
Trainable params: 2,369
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train,y_train,batch_size=128,epochs=100,shuffle=False,validation_split=0.1)

Train on 560 samples, validate on 63 samples
Epoch 1/100
560/560 [==============================] - 2s 3ms/step - loss: 0.7499 - accuracy: 0.4232 - val_loss: 0.7089 - val_accuracy: 0.5079
Epoch 2/100
560/560 [==============================] - 0s 47us/step - loss: 0.6803 - accuracy: 0.6071 - val_loss: 0.6632 - val_accuracy: 0.6984
Epoch 3/100
560/560 [==============================] - 0s 44us/step - loss: 0.6344 - accuracy: 0.7250 - val_loss: 0.6252 - val_accuracy: 0.7143
Epoch 4/100
560/560 [==============================] - 0s 42us/step - loss: 0.5947 - accuracy: 0.7536 - val_loss: 0.5948 - val_accuracy: 0.6984
Epoch 5/100
560/560 [==============================] - 0s 46us/step - loss: 0.5711 - accuracy: 0.7554 - val_loss: 0.5707 - val_accuracy: 0.6984
Epoch 6/100
560/560 [==============================] - 0s 47us/step - loss: 0.5436 - accuracy: 0.7857 - val_loss: 0.5518 - val_accuracy: 0.6984
Epoch 7/100
560/560 [==============================] - 0s 46us/step - loss: 0.5280 - accurac

#SVM

In [ ]:
from sklearn.svm import SVC
clf_svc = SVC(kernel='rbf',gamma=0.1,C=0.5)
clf_svc.fit(x_train,y_train)

SVC(C=0.5, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = clf_svc.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))

[[135  22]
 [ 26  85]]


In [ ]:
np.set_printoptions(precision=2)
print(accuracy_score(y_test,y_pred)*100)

82.08955223880598


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(clf_svc,x_train,y_train,cv=10)
print("acc={:.2f}".format(accuracies.mean()*100))
print("std={:.2f}".format(accuracies.std()*100))

acc=80.39
std=5.39


#Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
clf_nb = GaussianNB()
clf_nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred_nb = clf_nb.predict(x_train)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_train,y_pred_nb))

[[337  55]
 [ 95 136]]


In [ ]:
np.set_printoptions(precision=2)
print(accuracy_score(y_train,y_pred_nb)*100)

75.92295345104334


#Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
clf_reg = LogisticRegression()
clf_reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred_re = clf_reg.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred_re))

[[132  25]
 [ 37  74]]


In [ ]:
np.set_printoptions(precision=2)
print(accuracy_score(y_test,y_pred_re)*100)

76.86567164179104


#RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150,criterion='entropy')
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred_for = classifier.predict(x_test)
print(confusion_matrix(y_pred_for,y_test))

[[121  22]
 [ 36  89]]


In [ ]:
print(accuracy_score(y_pred_for,y_test))

0.7835820895522388
